### ISSUE TITLE
support custom json encoding flags

### ISSUE THREAD

**Issue by wbolster** [wbolster/jsonlines#10]
e.g. `sort_keys`

**Comment by wbolster** [comment]
what makes sense to have directly in this lib?

for writing:

* compact writing with minimal separator overhead; this translates to the `separators` arg to `json.dumps()`

* sorted keys, which can be used to produce deterministic output; this translates to the `sort_keys` arg to `json.dumps()`

for reading:

* nothing?


as an alternative to a few common built-in flags, perhaps a custom `dumps` and `loads` callable could be supported. that gives ultimate flexibility without sacrificing nice api for commaon cases. and it would also resolve #12 .

/cc @c-w since you're interested in this, thoughts?

**Comment by wbolster** [comment]
see #15 for a straight-forward implementation of these ideas.

@c-w please have a look

**Comment by c-w** [comment]
@wbolster #15 looks good to me. I'd add a test similar to [test_writer_json_kwargs](https://github.com/wbolster/jsonlines/pull/14/files#diff-c36c888a0b4247cb93a0d4b5f6c4071aR31) for the compact and sort arguments and then :ship:

**Comment by wbolster** [comment]
@c-w any chance you can test out current `master`? i think this lib has now matured enough to warrant a new release on pypi.
