### ISSUE TITLE
Make jsonlines.open() accept a data stream from network

### ISSUE THREAD

**Issue by saurabhKRocket** [wbolster/jsonlines#25]
Code Snippet:

```python
r = requests.get(<some-url>)
with jsonlines.open(r.content.decode()) as reader:
    for line in reader:
        print(line)
```

Expected Result:

```
Parsing every line as individual JSON object.
```

Current Result:

```
Can't read the network stream
```

Please let me know if such a feature can be included. If yes, I would love to talk and submit a PR.

**Comment by wbolster** [comment]
i think this is possible already.

your code is accessing .content, which means no streaming is done. also i do not recognise that error message. it certainly does not come from jsonlines chuffed since it does not do anything network related.

can you share a complete runnable code sample (i can stick in my own url) with an actual error traceback?

**Comment by saurabhKRocket** [comment]
Here is an actual error traceback:

(kreportPY) d3prof3t@saurabh:~/Work/kraftly_dwh$ python reporting/project/mixpanel_dump/resource/clevertap_data_export.py 
Traceback (most recent call last):
  File "reporting/project/mixpanel_dump/resource/clevertap_data_export.py", line 42, in <module>
    with jsonlines.open(r.content.decode()) as reader:
  File "/home/d3prof3t/.virtualenvs/kreportPY/lib/python3.5/site-packages/jsonlines/jsonlines.py", line 322, in open
    fp = io.open(name, mode=mode + 't', encoding='utf-8')
OSError: [Errno 36] File name too long: '{"event":"Users Within 0-5 Minutes","properties":{"time":1452556796,"distinct_id":"sabahsaeed75@gmail.com","$app_version":"1.0.3","$bluetooth_enabled":false,"$bluetooth_version":"classic","$brand":"samsung","$carrier":"INA-airtel","$city":"Delhi","$email":"sabahsaeed75@gmail.com","$google_play_services":"available","$has_nfc":false,"$has_telephone":true,"$lib_version":"4.5.3","$manufacturer":"samsung","$model":"GT-I9082","$name":"Sabah Saeed","$os":"Android","$os_version":"4.2.2","$region":"National Capital Territory of Delhi","$screen_dpi":240,"$screen_height":800,"$screen_width":480,"$username":"Sabah Saeed","$wifi":true,"KR App Version":"Unknown Version","Kart Items":"0","Last Online":"2015-10-11T23:37:41","Shop Name":"valleytruffle","mp_country_code":"IN","mp_lib":"android"}}\n{"event":"Users Within 15-20 Minutes","properties":{"time":1452556798,"distinct_id":"hatfieldsomer@gmail.com","$app_version":"1.1.2","$bluetooth_enabled":true,"$bluetooth_version":"ble","$brand":"lge","$carrier":"Sprint","$city":"Atlanta","$email":"hatfieldsomer@gmail.com","$google_play_services":"available","$has_nfc":true,"$has_telephone":true,"$lib_version":"4.5.3","$manufacturer":"LGE","$model":"LGLS991","$name":"Somer Hatfield","$os":"Android","$os_version":"6.0","$region":"Georgia","$screen_dpi":640,"$screen_height":2392,"$screen_width":1440,"$username":"Somer Hatfield","$wifi":false,"KR App Version":"1.1.2","Kart Items":"null","Last Online":"2016-01-11T04:41:29","Shop Name":"null","mp_country_code":"US","mp_lib":"android"}}\n'

**Comment by saurabhKRocket** [comment]
I have got it working without the package use.

```python
for line in r.iter_lines():
    data = json.loads(line.decode())
    print(type(data), data)
```

Although I'm still curious about the issue, how it can be done.

**Comment by wbolster** [comment]
eh... have you actually read the docs? i spent quite some time describing how things are supposed to be used. https://jsonlines.readthedocs.io/en/latest/

the `jsonlines.open()` function is only a convenience function for simple cases, namely those involving reading/writing a regular named file.

if you want to stream large downloads, read
http://docs.python-requests.org/en/master/user/advanced/#body-content-workflow

a `jsonlines.Reader()` does what you want:

```python
from contextlib import closing
import jsonlines
import requests

with closing(requests.get(url, stream=True)) as r:
    reader = jsonlines.Reader(r.iter_lines())
    for doc in reader:
        ...
```

but if you don't care about actually streaming downloads (it has downsides), use

```python
r = requests.get(url)
for doc in jsonlines.Reader(r.iter_lines):
    ...
```

**Comment by saurabhKRocket** [comment]
Okay, thanks a lot. This really helped.
Apologies for not going through the docs closely.

**Comment by wbolster** [comment]
you're welcome. glad to see this library used. :)
