### ISSUE TITLE
Specify BSD license type / Add copy to repo

### ISSUE THREAD

**Issue by pmlandwehr** [wbolster/jsonlines#27]
Per pypi and the metadata, `jsonlines` is licensed under a BSD license but it's unclear which one  - the two- or the three-clause. Going by the information in the [documentation](https://jsonlines.readthedocs.io/en/latest/#license), it's the three-clause, but would you consider adding a copy of the license to the repository itself? It'd also be helpful if you added a `MANIFEST.in` with an `include LICENSE.txt` line so that copies of the license get included in future source tarballs. Thanks!

**Comment by wbolster** [comment]
fixed in c446ee1

bumped version to 1.1.1 afterwards and pushed a new release to pypi: https://pypi.python.org/pypi/jsonlines
