### ISSUE TITLE
idea: method to load jsonlines file to list

### ISSUE THREAD

**Issue by refrigerator** [wbolster/jsonlines#32]
Hi,

Love the library. We're starting to use jsonlines as our de-facto format for storing datasets for data science, since it's useful for streaming and batch processing. What this means is that all the json objects in a given file are homogeneous, and we almost always want to load the objects into a list in Python. 

We've currently got our own (super simple) function to do this, but I imagine this is quite a common use-case so would be good for the library to have something like a `Reader().to_list()` function. 

What do you think? Happy to implement this and make a PR if you think it's a good idea.

**Comment by wbolster** [comment]
list(reader) will already do this thanks to python's iteration protocol: list(...) consumes any iterable, and jsonlines.Reader is iterable.

**Comment by wbolster** [comment]
oh, and thanks for the kind words, i appreciate that a lot ❤
