### ISSUE TITLE
Minify each line

### ISSUE THREAD

**Issue by josiekre** [wbolster/jsonlines#34]
I'd like to write something like:

```
 {"some":"thing"}
 {"foo":17,"bar":false,"quux":true}
 {"may":{"include":"nested","objects":["and","arrays"]}}
```

rather than:

```
 {"some": "thing"}
 {"foo": 17, "bar": false, "quux": true}
 {"may": {"include": "nested", "objects": ["and", "arrays"]}}
```

In short, the separators need to be `","` and `":"` rather than `", "` and `": "`. Is this possible currently?

**Comment by wbolster** [comment]
also the usefulness of stripping whitespace at the cost of readability is debatable. if you're after saving some space, any lightweight compression algorithm like gzip/zlib with minimal compression will give significantly better space savings with negligible overhead.

**Comment by josiekre** [comment]
Does jsonlines write gzip? Or do you suggest compressing after writing if using jsonlines?

**Comment by josiekre** [comment]
Pinging again on this question. My normal approach with gzip is:

```
with gzip.open(path.people(), 'rt') as f:
    # read
```

That pattern does not hold with `jsonlines`. Sorry for the relatively straightforward question!

**Comment by wbolster** [comment]
`gzip.open()` returns a "file-like object", and those can be used by the jsonlines.Reader and Writer.

```python
reader = jsonlines.Reader(f, ...)
for obj in reader:
    ...
```

the docs have some more details about this.

`jsonlines.open()` cannot be used here since that's only for the simplest of cases. but if you look inside that function you'll see that it does something similar: it opens a file, then passes it along to a reader (or writer).

hth.

**Comment by josiekre** [comment]
Thanks that's exactly what I needed!

**Comment by wbolster** [comment]
cool. :tulip:   i would be interested to hear actual numbers for a sample of your data:

- uncompressed size
- size with `compact=True`
- size with basic gzip compression

(btw if you really care about size and you don't care about significant cpu use: use `xz` (`import lzma`) instead of `gzip`)

**Comment by AlJohri** [comment]
@wbolster is it easy to directly append to a json.gz file?

**Comment by wbolster** [comment]
@aljohri this seems unrelated. please open a new issue.
