### ISSUE TITLE
ModuleNotFound error even after installing jsonlines

### ISSUE THREAD

**Issue by yasimk** [wbolster/jsonlines#48]
I am getting ModuleNotFound error even after installing jsonlines. I am trying to run the python program (Python 3.6) using JupyterLab in AWS SageMaker. Here are the steps. Can you please help?

1) Install jsonlines
!pip install jsonlines

2) Import jsonlines library
import jsonlines

3) Error occurred
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-0bb7078641ac> in <module>()
      6 
      7 import boto3
----> 8 import jsonlines
      9 import matplotlib
     10 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'jsonlines'

**Comment by yasimk** [comment]
Fixed the issue by pointing the environment to conda_python3 instead of conda_pytorch_p36.

**Comment by wbolster** [comment]
cool 🙃
