### ISSUE TITLE
comparison with json-lines

### ISSUE THREAD

**Issue by dcsanx** [wbolster/jsonlines#50]
Hi! Sorry to ask this here, but I find it hard to see differences. is there a different problem this is solving, or feature comparison vs. this package:

https://github.com/TeamHG-Memex/json-lines

**Comment by wbolster** [comment]
hmmm lemme have a look.

this package reads and writes and has features like reading from any iterable, not just files. it can also do type checking and more detailed error reporting. and it can do some other niche things. compressed files can be used by using normal python wrappers for that, which the python stdlib provides.

i had a quick look at the other package and it seems it only supports reading from files. it has special handing for recovering data from broken gzip files.

in my opinion, gzip recovery/data salvation is unrelated to jsonlines handling, and it could be implemented as stand-alone recovery code, which is then fed into this library afterwards.

the same goes for reporting/logging/whatever of broken input lines. this can be implemented quite easily with a few lines of code on top of this library as well.

**Comment by dcsanx** [comment]
super, thanks so much for taking the time!

**Comment by wbolster** [comment]
you're welcome!
