### ISSUE TITLE
jsonlines.Writer encoding an alternative codec to UTF-8

### ISSUE THREAD

**Issue by noamsgl** [wbolster/jsonlines#52]
Feature suggestion:

Enable the `jsonlines.Writer.write(self, obj)` to receive another parameter - encoding which allows the user to specify the output encoding.

Right now reading the output.jsonl filethat I dumped, looks as follows:

>  President Trump was seeking the \u201cultimate deal\u2014 in the Middle East 

What I would like to see:

>  President Trump was seeking the “ultimate deal” in the Middle East

**Comment by wbolster** [comment]
can you share example code exhibiting your problem? since i think your problem is elsewhere...

this example (tested using python 3.8.2):

```python
>>> import jsonlines
>>> with jsonlines.open('out.jsonl', 'w') as writer:
...     writer.write({"test": "here is a snowman: \u2603"})
```

...creates a file like this:

```
$ cat out.jsonl 
{"test": "here is a snowman: ☃"}
```

...which is correct!
