### ISSUE TITLE
Document the issues of handling JSON Lines without this library

### ISSUE THREAD

**Issue by Gallaecio** [wbolster/jsonlines#53]
I recently learned that using `splitlines` to split the lines of a JSON Lines file is a bad idea, because [there are characters that do not need to be escaped in JSON, such as `NEL` (`0x85`)](https://stackoverflow.com/questions/17614613/are-newlines-guaranteed-to-be-escaped-in-json/22984589#22984589), which `splitlines` interprets as line separators.

Since this project looks like it has the potential of becoming the go-to library to handle JSON Lines in Python, I think it would be great to eventually extend the documentation to explain some of these issues that this library solves. Just so that, for example, when [someone recommends using `splitlines` to split JSON Lines files](https://stackoverflow.com/a/61184208/939364), or [reports issues due to using `splitlines`](https://github.com/saltstack/salt/issues/57916), a link to such a documentation page can be shared for details.

**Comment by wbolster** [comment]
oh wow, thanks. i wasn't aware of such issues at all. never encountered that in practice 😌

``` python
>>> s = '["first\x85"]\n["second"]'
```

it seems this is only a problem for `str.splitlines()`, which `jsonlines` itself doesn't do fortunately:

``` python
>>> s.splitlines()
['["first', '"]', '["second"]']
>>> len(s.splitlines())  # oops,
3
```

file-like objects don't seem to suffer from the problem:

``` python
>>> for x in io.StringIO(s): print(repr(x))
'["first\x85"]\n'
'["second"]'
```

if you have any practical ideas on how to improve docs, let me know, e.g. as a pull request.
