### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by BastianZim** [wbolster/jsonlines#56]
Hi,

thanks for creating this great package!

I was wondering if you would mind if I add this to [conda-forge](https://conda-forge.org) so that it can be downloaded using [conda](https://en.wikipedia.org/wiki/Conda_(package_manager))?

Thanks!

**Comment by BastianZim** [comment]
I would add you not the feedstock as a maintainer, if you're interested. Otherwise I would maintain it myself.

**Comment by wbolster** [comment]
:pray:  by all means, please add it, since this library is growing in popularity. on pypi this library has ~500k downloads a month currently (https://pepy.tech/project/jsonlines)

**Comment by BastianZim** [comment]
Perfect, will do! Would you like to be a maintainer there as well? Just means updating it if there is a new version etc.

**Comment by BastianZim** [comment]
Also, should I add a badge (and instructions?) to the README for this, once added?

**Comment by wbolster** [comment]
feel free to add me as a maintainer, though i might forget to update things (i have too many projects and too little time :wink:). do i need an account for that?

and sure, badge welcome!

**Comment by BastianZim** [comment]
Haha no worries will do. No, everything's on GitHub.

Ok perfect, will add!

**Comment by BastianZim** [comment]
Apparently, there's already a package but it's not being updated. I'll ping the maintainer and add the badge here. https://github.com/conda-forge/jsonlines-feedstock

If you still would like to be added as a maintainer, you'd have to contact him directly as I'm not associated with that feedstock.
