### ISSUE TITLE
Only reads one line.

### ISSUE THREAD

**Issue by Grumpypjs08** [wbolster/jsonlines#67]
My function only reads one line:
code:
`with jsonlines.open('file.json') as reader:
        for obj in reader:

            etc.......
            return 'Success!'`
json:
`{"id":1,"original_name":"プライド","popularity":3.816}
{"id":2,"original_name":"Clerks: The Animated Series","popularity":10.471}
{"id":3,"original_name":"The Message","popularity":0.6}
{"id":4,"original_name":"The Amazing Mrs Pritchard","popularity":5.867}
{"id":5,"original_name":"La Job","popularity":7.533}
{"id":6,"original_name":"Strange Days at Blake Holsey High","popularity":5.39}`

**Comment by Grumpypjs08** [comment]
the return is in the rong spot

**Comment by wbolster** [comment]
you're welcome 😜
