### ISSUE TITLE
Jsonlines open mode 'w+' ?

### ISSUE THREAD

**Issue by Kleart** [wbolster/jsonlines#72]
Hello,
Thank you for developing this handy library!

I have a use case where I need to open a jsonline file or create it on the fly in order to write into it. I browsed the source code and if I am not wrong the only open modes are w,r,a . I can try to contribute, but since I don't think I have the skills to do it I may need some assistance.

**Comment by Kleart** [comment]
I need to open an existing file or create it, like using open() in standard library. 

f = open('file.txt' , 'w+')

I tried to find a way how to do it using jsonlines, but I couldn't find one.
I can change the issue description, since it may be misleading.

**Comment by wbolster** [comment]
i think you're looking for 'a'. what makes you think you need 'w+'?
