### ISSUE TITLE
Allow file create ('x') mode

### ISSUE THREAD

**Issue by david-waterworth** [wbolster/jsonlines#74]
From python 3.3 I believe the `builtins.open()` method now supports mode=`x` representing create (if the file exists an error is thrown).

`jsonlines.open()` only allows mode in 'r', 'w' and 'a', otherwise a ValueError is rased, despite it being a valid mode - i.e. the following works fine.

```
with open(f'experiments/clf/data/train.jsonl', mode="xt", encoding="utf-8") as fp:
    writer = jsonlines.Writer(fp)
    writer.write_all(train)
```

Also note pylance defines the following

OpenTextModeWriting: TypeAlias = Literal["w", "wt", "tw", "a", "at", "ta", "x", "xt", "tx"]
OpenTextModeReading: TypeAlias = Literal["r", "rt", "tr", "U", "rU", "Ur", "rtU", "rUt", "Urt", "trU", "tUr", "Utr"]

You could use these to validate the mode

**Comment by wbolster** [comment]
good idea! implemented via 2f2bb478496cf8e9cb7f39424bfda6ea4dc5c440

included in just released 3.1.0 version, so you should upgrade 😁
