### ISSUE TITLE
Update release info

### ISSUE THREAD

**Issue by pb-jeff-oneill** [wbolster/jsonlines#94]
Hello!  pypi shows 4.0.0 but the latest release shown here is 3.0.0 (3.1.0) is also missing.

It would be great if you could show the releases here so we know what changes have happened.  When upgrading, I want to be sure to not break production code.

**Comment by wbolster** [comment]
sorry, i forgot to push the git tag.

changelog is here: https://jsonlines.readthedocs.io/en/latest/#version-history

i don't use the github releases pages b/c it's too much hassle. i just removed the (outdated) release from that page.

**Comment by pb-jeff-oneill** [comment]
Thank you Wouter, much appreciated.

And thank you for maintaining this project!
