### ISSUE TITLE
Add a command line executable

### ISSUE THREAD

**Issue by yaniv-aknin** [wbolster/jsonlines#95]
I'd like to suggest the addition of a CLI tool to jsonlines, which will be a "jsonl command line swiss army knife".

I'm imagining something with this behaviour -
```console
$ cat sample.jsonl 
{"id": 0, "label": "spam"}
{"id": 1, "label": "eggs"}
{"id": 2, "label": "ham"}
$ jsonlines fromlines sample.jsonl
[{"id": 0, "label": "spam"}, {"id": 1, "label": "eggs"}, {"id": 2, "label": "ham"}]
$ jsonlines fromlines sample.jsonl | jsonlines tolines
{"id": 0, "label": "spam"}
{"id": 1, "label": "eggs"}
{"id": 2, "label": "ham"}
$ mkdir -p samples/{spam,eggs,ham}
$ jsonlines tojsons --key label --filename metadata.json --indent 4 sample.jsonl
$ cat samples/spam/metadata.json
{
    "id": 0,
    "label": "spam"
}
$ jsonlines fromjsons samples/*/metadata.json
{"id": 0, "label": "spam"}
{"id": 1, "label": "eggs"}
{"id": 2, "label": "ham"}
$
```

This session demonstrates -
* Converting from/to jsonl to array of objects
* Converting from/to bunch of .json files to a .jsonl stream

I find the latter (bunch of .json files to/from .jsonl stream) to be particularly useful pattern when dealing with binary blobs, such as a collection of media files (movies, pictures, etc) or in scientific applications (physics, medicine, biology etc). One can imagine a directory of many data observations, each stored in its own subdirectory, with a metadata.json file sitting in that subdirectory and describing the specific observation or a repository.jsonl file in the toplevel directory describing all observations.

I'm willing to contribute this code and send a pull request, also happy to discuss what sort of CLI behaviour you'd find appealing. Since it's not obvious `jsonlines` would like this functionality, I first wanted to gauge your interest. I think Python libraries having such a tool is pretty common (`python -m json.tool`, `python -m http.server`, ...) and it could be installed used with pipx.

Another potential home for this functionality is [`petl`](https://petl.readthedocs.io/en/stable/), which already [has](https://petl.readthedocs.io/en/stable/intro.html#petl-executable) an accompanying tool.

**Comment by wbolster** [comment]
i think jq already covers what you describe, and much much MUCH more

**Comment by yaniv-aknin** [comment]
Thanks, I didn't know `jq` can read multiple indented files and turn them into a jsonl stream, this is perhaps the most important thing I was missing.

I'm still not sure how to do the inverse -- go from a jsonl stream to many metadata.json files (what `jsonlines tojsons --key label --filename metadata.json --indent 4 sample.jsonl` does in the example), but I agree that's even if `jq` doesn't do it, this is the most tenuous feature in this request and doesn't really fit in `jsonlines`.

**Comment by wbolster** [comment]
i think shell tools like `split(1)`, combined with jq, can write multiple files?

https://www.gnu.org/software/coreutils/manual/html_node/split-invocation.html

**Comment by yaniv-aknin** [comment]
Don't think so, not if you need to split by some key in the JSON (in the example above, the `label` value needs to go in the file path). But it's fine, using `jq` in the "many indented JSON files to one JSONL" will be quite useful, and I'm quite sold the other direction doesn't fit `jsonlines`. Thanks for the suggestions!
